### ISSUE TITLE
CQ4: Preserve affiliation identifiers

### ISSUE THREAD

**Issue by stain** [ResearchObject/ro-crate-zenodo#4]
Assume the RO-Crate uploaded to Zenodo have used an ROR identifier as in https://www.researchobject.org/ro-crate/1.1/contextual-entities.html#organizations-as-values e.g. https://ror.org/03f0f6041 

The Zenodo entry should likewise have this identifier set on the affiliation, as is possible in the HTML form (but with an awkward auto-complete).  It may be that the full-text shown for the organization in the form is different from what is in the RO-Crate (typically for an institution with names in multiple languages or acronyms), it's not certain if it's possible to override this in the Zenodo API.

**Comment by elichad** [comment]
Currently this doesn't seem to be possible with the Zenodo API. It's possible with the _InvenioRDM_ API, but how the Zenodo API differs from that (and whether there's a way to pass Invenio-formatted data through) isn't well documented at the moment.

**Comment by elichad** [comment]
Not planned, will be supported in https://github.com/ResearchObject/ro-crate-inveniordm
